routes/web.php
<?php

use Muntadaa\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('discussions', 'DiscussionsController');

Route::resource('discussions/{discussion}/replies', 'RepliesController');

Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@bestReply')->name('discussions.best-reply');

Route::get('users/notifications', [UsersController::class, 'notifications'])->name('user.notifications');

Route::resource('channels', 'ChannelsController');

app/User.php
<?php

namespace Muntadaa;

use Muntadaa\Reply;
use Muntadaa\Discussion;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function discussions(){
        return $this->hasMany(Discussion::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace Muntadaa\Http\Controllers;

use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function notifications()
    {
        //mark all as read
        auth()->user()->unreadNotifications->markAsRead();

        //display all notifications
        return view('users.notifications')->with('notifications', auth()->user()->notifications);

    }
}

resources/views/users/notifications.blade.php
@extends('layouts.app')

@section('content')


<div class="card">
        <div class="card-header">Notifications</div>

        <div class="card-body">
            <ul class="list-group">
            @foreach ($notifications as $notification)
                    <li class="list-group-item">
                    @if ($notification->type == 'Muntadaa\Notifications\NewReplyAdded' )
                        A new notitication was added to your <strong> {{ $notification->data['discussion']['title'] }} </strong> discussion
                        <a href="{{ route('discussions.show', $notification->data['discussion']['slug']) }}" class="btn btn-info btn-sm float-right"> View discussion </a>
                    @endif
                    @if($notification->type == 'Muntadaa\Notifications\BestReply')
                        Your reply to the discussion <strong>{{ $notification->data['discussion']['title'] }}</strong> was marked as best!
                        <a href="{{ route('discussions.show', $notification->data['discussion']['slug']) }}" class="btn btn-info btn-sm float-right"> View discussion </a>
                    @endif
                    </li>
            @endforeach
            </ul>
        </div>
    </div>
@endsection