routes/web.php
<?php

use Muntadaa\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('discussions', 'DiscussionsController');

Route::resource('discussions/{discussion}/replies', 'RepliesController');

Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@bestReply')->name('discussions.best-reply');

Route::get('users/notifications', [UsersController::class, 'notifications'])->name('user.notifications');

Route::resource('channels', 'ChannelsController');

app/Discussion.php
<?php

namespace Muntadaa;

use Muntadaa\User;
use Muntadaa\Reply;
use Muntadaa\Channel;
use Muntadaa\Notifications\BestReply;

class Discussion extends InheritedModel
{
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function bestReply()
    {
        return $this->belongsTo(Reply::class, 'reply_id');
    }


    public function markAsBestReply(Reply $reply)
    {
        $this->update([
            'reply_id' => $reply->id

        ]);

        if($reply->owner->id == $this->author->id) {
            return;
        }

        $reply->owner->notify(new BestReply($reply->discussion));


    }

    public function scopeFilterByChannels($builder)
    {
        if(request()->query('channel'))
        {
            $channel = Channel::where('slug', request()->query('channel'))->first();

            if($channel) {
                return $builder->where('channel_id', $channel->id);
            }

            return $builder;

        }

        return $builder;
    }
}

app/Http/Controllers/DiscussionsController.php
<?php

namespace Muntadaa\Http\Controllers;

use Muntadaa\Reply;
use Muntadaa\Discussion;
use Illuminate\Http\Request;
use Muntadaa\Http\Requests\CreateDiscussionRequest;

class DiscussionsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified'])->only(['create', 'store']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('discussions.index', [
            'discussions' => Discussion::filterByChannels()->paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discussions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDiscussionRequest $request)
    {
        auth()->user()->discussions()->create([
            'title' => $request->title,
            'channel_id' => $request->channel,
            'content' => $request->content,
            'slug' => str_slug($request->title)
            // 'user_id' => auth()->user()->id
        ]);

        session()->flash('success', 'Discussion added suscessfully');

            return redirect()->route('discussions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Discussion $discussion)
    {
         return view('discussions.show', [
            'discussion' => $discussion
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function bestReply(Discussion $discussion, Reply $reply)
    {
        $discussion->markAsBestReply($reply);

        session()->flash('success', 'Marked as best reply');

        return redirect()->back();
    }
}

resources/views/discussions/channel-discussions.blade.php
@extends('layouts.app')

@section('content')

@foreach ($discussions as $discussion)

    <div class="card">
        @include('partials.discussion-header')

                <div>
                    <a href="{{ route('discussions.show', $discussion->slug) }}" class="btn btn-success btn.sm">View</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="text-center">
                <strong> {{ $discussion->title }} </strong>
            </div>
        </div>
    </div>

@endforeach


@endsection

resources/views/discussions/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">Add Discussion</div>
        <div class="card-body">
            <form action="{{ route('discussions.store') }}" method="post">
                @csrf

                <div class="form-group">
                    <label for="title">Title</label>
                    <input class="form-control" type="text" name="title" id="title" value="">
                </div>
                <div class="for-group">
                    <label for="channel">Select A Channel</label>
                        <select class="form-control" name="channel" id="channel">
                            @foreach ($channels as $channel)
                            <option value="{{ $channel->id }}">{{ $channel->name }}</option>
                            @endforeach
                        </select>
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    {{-- <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea> --}}
                    <input id="content" type="hidden" name="content">
                    <trix-editor input="content"></trix-editor>
                </div>
                   <button class="btn btn-success" type="submit">Create Discussion</button>
            </form>
        </div>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.1/trix.css">
@endsection

@section('js')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.1/trix.js"></script>
@endsection

resources/views/discussions/index.blade.php
@extends('layouts.app')

@section('content')

@foreach ($discussions as $discussion)

    <div class="card">
        @include('partials.discussion-header')

                <div>
                    <a href="{{ route('discussions.show', $discussion->slug) }}" class="btn btn-success btn.sm">View</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="text-center">
                <strong> {{ $discussion->title }} </strong>
            </div>
        </div>
    </div>

@endforeach
    {{ $discussions->appends(['channel' => request()->query('channel') ])->links() }}

@endsection

resources/views/discussions/show.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
        @include('partials.discussion-header')
            <div>
                <h5><strong>{{ $discussion->title }}</strong></h5>
            </div>
        </div>
    </div>

    <div class="card-body">
        {!! $discussion->content  !!}
    </div>
    @if ($discussion->bestReply)
    <div class="card border-success mb-3" style="max-width: 75%;">
        <div class="card-header">
            <img src="{{ Gravatar::src($discussion->bestReply->owner->email)  }}" alt="" width="15px" height="15px" style="border-radius: 50%">
            <strong> Best reply so far! </strong> || Thanks to: {{ $discussion->bestReply->owner->name }}
        </div>

        <div class="card-body">
           <p class="card-text"> {!! $discussion->bestReply->content !!} </p>
        </div>
    </div>

    @endif

    @if ($discussion->replies()->count() > 0)

        <div class="card">
            <div class="card-header mb-2">
                <h4><strong>Replies</strong></h4>
            </div>
        </div>
    @endif

    @foreach ($discussion->replies()->paginate(3) as $reply)

    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <div>
                    <img src="{{ Gravatar::src($reply->owner->email) }}" alt="" width="20px" height="20px" style="border-radius: 50%">
                    <span>
                     {{ $reply->owner->name }}
                    </span>
                </div>
                <div>
                    @if (auth()->user() == $discussion->author)
                        <form action="{{ route('discussions.best-reply', ['discussion' => $discussion->slug, 'reply' => $reply->id]) }}" method="post">
                            @csrf
                            <button type="submit" class="btn btn-success btn-sm">Mark as best reply</button>
                        </form>
                    @endif
                </div>
            </div>
        </div>

        <div class="card-body">
            {!! $reply->content !!}
        </div>

    </div>

    @endforeach

    {{ $discussion->replies()->paginate(3)->links() }}

    <div class="card-body">
       @auth
            <form action="{{ route('replies.store', $discussion->slug) }}" method="post">
            @csrf
                <div class="form-group">
                    <input id="reply" type="hidden" name="reply">
                    <trix-editor input="reply"></trix-editor>
                </div>
                <button class="btn btn-success" type="submit">Add a Reply</button>
            </form>
       @else
        <a href="{{ route('login') }}" class="btn btn-info my-2" style="width: 100%; color: #fff ">Sign-in to Add Reply</a>
       @endauth
    </div>


</div>

@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.1/trix.css">
@endsection

@section('js')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.1/trix.js"></script>
@endsection